# Kurulum Aşaması

In [37]:
import torch
print(torch.__version__)

2.11.0+cpu


In [38]:
import torch

print("PyTorch sürümü:", torch.__version__)
print("CUDA kullanılabiliyor mu:", torch.cuda.is_available())

PyTorch sürümü: 2.11.0+cpu
CUDA kullanılabiliyor mu: False


In [39]:
import torch

x = torch.tensor([1, 2, 3])
print(x)
print(x * 2)

tensor([1, 2, 3])
tensor([2, 4, 6])


In [40]:
print(torch.cuda.is_available())

False


# Temel İşlemler

In [41]:
import torch

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


### NumPy karşılığı:

In [42]:
import numpy as np

x = np.array([1, 2, 3])

## Shape

In [43]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


### NumPy karşılığı:

In [44]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


## dtype

In [45]:
x = torch.tensor([1,2,3])
print(x.dtype)

torch.int64


In [46]:
x = torch.tensor([1,2,3], dtype=torch.float32)
print(x.dtype)

torch.float32


### NumPy karşılığı:

In [47]:
x = np.array([1,2,3], dtype=np.float32)

# Tensor oluşturma (farklı yollar)

In [48]:
#manuel
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [49]:
#sıfırlar
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
#birler
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [51]:
#random
torch.rand(2,3)

tensor([[0.8455, 0.2804, 0.3940],
        [0.1085, 0.6459, 0.7763]])

# Temel işlemler

In [52]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
