# Autograd: Gradyan hesaplama

In [19]:
import torch

x = torch.tensor(3.0, requires_grad=True) # requires_grad=True: PyTorch, bu değişkenin türevini hesaplamak için bunu takip et demek
y = x ** 2

print("x =", x)
print("y =", y)

x = tensor(3., requires_grad=True)
y = tensor(9., grad_fn=<PowBackward0>)


In [20]:
y.backward()  # y’nin x’e göre türevini hesapla

print("x.grad =", x.grad)

x.grad = tensor(6.)


# Matris çarpımı

In [21]:
import torch

A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

C = torch.matmul(A, B)  # matris çarpımı yapar

print("A =")
print(A)

print("B =")
print(B)

print("A x B =")
print(C)

A =
tensor([[1, 2],
        [3, 4]])
B =
tensor([[5, 6],
        [7, 8]])
A x B =
tensor([[19, 22],
        [43, 50]])


# Reshape

In [22]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])

print("Eski hali:")
print(x)

print("Eski shape:")
print(x.shape)

y = x.reshape(2, 3)  # tensorün boyutunu değiştiri

print("Yeni hali:")
print(y)

print("Yeni shape:")
print(y.shape)

Eski hali:
tensor([1, 2, 3, 4, 5, 6])
Eski shape:
torch.Size([6])
Yeni hali:
tensor([[1, 2, 3],
        [4, 5, 6]])
Yeni shape:
torch.Size([2, 3])


# Slicing

In [23]:
import torch

x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print("Orijinal tensor:")
print(x)

print("İlk satır:")
print(x[0])                                #tensorün içinden istediğin parçayı alma

print("İkinci satırın üçüncü elemanı:")
print(x[1, 2])

print("İlk iki satır ve ilk iki sütun:")
print(x[:2, :2])

Orijinal tensor:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
İlk satır:
tensor([10, 20, 30])
İkinci satırın üçüncü elemanı:
tensor(60)
İlk iki satır ve ilk iki sütun:
tensor([[10, 20],
        [40, 50]])
